from __future__ import annotations

from typing import Any

ACTOR_OVERLAY_TYPES = {
    "lid_state",
    "performative_blink",
    "blink_suppression",
}


def export_actor_overlay_events(resolved_events: dict[str, Any], clip_name: str = "") -> dict[str, Any]:
    """Export non-JALI, non-gaze actor overlay events.

    These events are generated by the full_actor annotator profile. They are not
    sent to JALI Text Editor. A later Maya adapter can use this file to implement
    eyelid baseline changes, performative blinks, and blink suppression gates.
    """
    events: list[dict[str, Any]] = []
    for event in resolved_events.get("events", []):
        event_type = event.get("type")
        if event_type not in ACTOR_OVERLAY_TYPES:
            continue
        events.append(
            {
                "id": event.get("id"),
                "type": event_type,
                "value": event.get("value"),
                "text": event.get("text", ""),
                "reason": event.get("reason", ""),
                "span": event.get("span"),
                "resolved_time": event.get("resolved_time"),
            }
        )

    return {
        "clip_name": clip_name,
        "events": events,
        "diagnostics": resolved_events.get("diagnostics", {}),
    }
